<?php

function views_select_views_plugins() {
  return array(
    'style' => array(
      'views_select' => array(
        'title' => t('Table select'),
        'help' => t('Views'),
        'handler' => 'view_select_plugin_style_views_select',
        'parent' => 'table',
        'theme' => 'views_view_table',
        'uses row plugin' => FALSE,
        'uses fields' => TRUE,
        'uses options' => TRUE,
        'type' => 'normal',
        'help topic' => 'style-table',
        'theme path' => drupal_get_path('module', 'views') .'/theme'
      ),
    ),
  );
}

function views_select_preprocess_views_view_table(&$vars) {
  $m = drupal_get_path('module','views_select');
  drupal_add_js("$m/js/table_select.js");
  drupal_add_js("$m/js/views_select.js");
  drupal_add_css("$m/css/views_select.css");
  $view = $vars['view'];
  
  $settings = array();
  $settings['view_name'] = $view->name;
  $settings['table_sel'] = ".view-{$settings['view_name']} table.views-table";
  $col = str_replace('_','-',$vars['options']['value_col']);
  $settings['value_col_sel'] = "td.views-field-$col";
  $settings['callback'] = "{$vars['options']['jscallback']}";
  
  drupal_add_js(
    array(
      'views_select' => array(
        $settings['view_name'] => $settings,
      ),
    ),
    'setting'
  );
}
